# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: amanjaiswal7236
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: internship
# "service" is the name of this project. This will also be added to your AWS resource names.
service: email-service

provider:
  name: aws
  runtime: nodejs20.x

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000

iamRoleStatements:
  - Effect: Allow
    Action:
      - ses:SendEmail
    Resource: "*"
